/* SPDX-License-Identifier: Apache-2.0
 * Pinyin → Unicode candidate table for Bafang IME.
 *
 * 334 Mandarin syllables, 1359 total candidate codepoints.
 * Sorted by syllable string — binary-searchable in O(log 334) ≈ 9 steps.
 * All data is const and lives in MCU Flash (.rodata); zero SPI reads required
 * for IME lookup (contrast: Dondji's linear SPI scan ≈ 1000 reads/keystroke).
 *
 * Generated by:  tools/extract_pinyin.py --dondji <k5-dondji/cn_font_data.h>
 */

#ifndef IME_PINYIN_TABLE_H
#define IME_PINYIN_TABLE_H

#include <stdint.h>

/* Maximum length of any syllable string (e.g. "zhuang" = 6 chars + NUL). */
#define PY_SYLLABLE_MAX   8u

/* One entry in the sorted pinyin lookup table. */
typedef struct {
    char     syllable[PY_SYLLABLE_MAX]; /* null-terminated ASCII syllable       */
    uint8_t  count;                     /* number of Unicode candidate chars    */
    uint16_t offset;                    /* start index into kPyCandidates[]     */
} PinyinEntry_t;

/* Sorted table — use PY_BSearch() rather than accessing directly. */
extern const PinyinEntry_t kPyTable[];
extern const uint16_t      kPyTableLen;       /* 334 */

/* Flat candidate array: kPyTable[i].codepoints → kPyCandidates + offset. */
extern const uint16_t      kPyCandidates[];
extern const uint16_t      kPyCandidatesLen;  /* 1359 */

/* Binary search.
 * Returns pointer to the matching entry, or NULL if the syllable is not found.
 * Case-sensitive; syllable must be lower-case ASCII. */
const PinyinEntry_t *PY_BSearch(const char *syllable);

#endif /* IME_PINYIN_TABLE_H */
