/* Auto-generated by tools/extract_pinyin.py — do not edit.
 * Regenerate:
 *   python3 tools/extract_pinyin.py \
 *       --dondji /path/to/k5-dondji/App/cn_font_data.h \
 *       --out App/ime/pinyin_table.c
 *
 * Table: 334 syllables, 1359 total codepoints.
 * Sorted by syllable string (binary search in O(log 334) ≈ 9 steps).
 * All data is const, placed in MCU Flash (.rodata) — zero SPI reads for lookup.
 *
 * Source: Dondji cn_font_data.h, codepoint extraction via font-index comments.
 * SPDX-License-Identifier: Apache-2.0
 */

#include "ime/pinyin_table.h"

/* Flat array of all candidate Unicode codepoints.
 * kPyTable[i].offset is the start index; kPyTable[i].count is the length. */
const uint16_t kPyCandidates[] = {
    0x554Au, 0x963Fu, 0x9698u, 0x7231u, 0x5B89u, 0x6697u, 0x6309u, 0x5CB8u,
    0x978Du, 0x50B2u, 0x6FB3u, 0x516Bu, 0x575Du, 0x628Au, 0x5DF4u, 0x62D4u,
    0x9738u, 0x9C85u, 0x5427u, 0x767Eu, 0x767Du, 0x67CFu, 0x4F70u, 0x534Au,
    0x677Fu, 0x73EDu, 0x7248u, 0x5E2Eu, 0x699Cu, 0x868Cu, 0x4FDDu, 0x62A5u,
    0x5305u, 0x5821u, 0x5B9Du, 0x8912u, 0x9C8Du, 0x5317u, 0x88ABu, 0x80CCu,
    0x5907u, 0x7891u, 0x8D1Du, 0x9642u, 0x672Cu, 0x6BD5u, 0x58C1u, 0x5FC5u,
    0x6BD4u, 0x78A7u, 0x95EDu, 0x8FB9u, 0x8868u, 0x6807u, 0x5BBEu, 0x6EE8u,
    0x5175u, 0x6CE2u, 0x64ADu, 0x8584u, 0x73BBu, 0x4EB3u, 0x535Au, 0x9A73u,
    0x4E0Du, 0x5E03u, 0x6B65u, 0x90E8u, 0x57D7u, 0x57E0u, 0x8521u, 0x83DCu,
    0x5F69u, 0x624Du, 0x88C1u, 0x9910u, 0x4ED3u, 0x6CA7u, 0x82CDu, 0x66F9u,
    0x8349u, 0x6D4Bu, 0x4FA7u, 0x5C91u, 0x5C42u, 0x67E5u, 0x8336u, 0x5DEEu,
    0x67F4u, 0x7985u, 0x957Fu, 0x5E38u, 0x5382u, 0x573Au, 0x660Cu, 0x5DE2u,
    0x6F6Eu, 0x8D85u, 0x8F66u, 0x9648u, 0x6668u, 0x90F4u, 0x6210u, 0x7A0Bu,
    0x6A59u, 0x79F0u, 0x57CEu, 0x627Fu, 0x4E58u, 0x6C60u, 0x8D64u, 0x6301u,
    0x577Bu, 0x9A70u, 0x866Bu, 0x5145u, 0x5D07u, 0x7EF8u, 0x51FAu, 0x50A8u,
    0x9664u, 0x695Au, 0x6EC1u, 0x5DDDu, 0x8239u, 0x7A97u, 0x6625u, 0x74F7u,
    0x6148u, 0x4ECEu, 0x7C97u, 0x6751u, 0x5B58u, 0x9519u, 0x5927u, 0x6253u,
    0x8FBEu, 0x5E26u, 0x5F85u, 0x6DE1u, 0x510Bu, 0x4E39u, 0x90F8u, 0x5355u,
    0x515Au, 0x5F53u, 0x7800u, 0x5230u, 0x9053u, 0x5C9Bu, 0x5012u, 0x5BFCu,
    0x7684u, 0x5FB7u, 0x9093u, 0x767Bu, 0x7B49u, 0x706Fu, 0x5730u, 0x7B2Cu,
    0x5E95u, 0x4F4Eu, 0x5F1Fu, 0x8FEAu, 0x6EC7u, 0x70B9u, 0x7535u, 0x5DC5u,
    0x5178u, 0x57ABu, 0x5E97u, 0x7538u, 0x540Au, 0x4E01u, 0x9876u, 0x9F0Eu,
    0x53EEu, 0x5B9Au, 0x4E1Cu, 0x8463u, 0x680Bu, 0x6D1Eu, 0x52A8u, 0x51ACu,
    0x549Au, 0x8C46u, 0x6597u, 0x7AA6u, 0x90FDu, 0x675Cu, 0x8BFBu, 0x5EA6u,
    0x72ECu, 0x77EDu, 0x65ADu, 0x6BB5u, 0x7F0Eu, 0x7AEFu, 0x5BF9u, 0x961Fu,
    0x58A9u, 0x6566u, 0x5428u, 0x591Au, 0x6735u, 0x9102u, 0x9E45u, 0x6069u,
    0x4E8Cu, 0x5C14u, 0x6D31u, 0x8033u, 0x513Fu, 0x53D1u, 0x6CD5u, 0x8FD4u,
    0x8303u, 0x53CDu, 0x7E41u, 0x756Au, 0x9632u, 0x623Fu, 0x653Eu, 0x65B9u,
    0x574Au, 0x82B3u, 0x90A1u, 0x98DEu, 0x80A5u, 0x975Eu, 0x7C89u, 0x5206u,
    0x6C7Eu, 0x82ACu, 0x51AFu, 0x98CEu, 0x5CF0u, 0x51E4u, 0x4E30u, 0x5949u,
    0x5C01u, 0x70FDu, 0x8702u, 0x4F5Bu, 0x798Fu, 0x5085u, 0x526Fu, 0x670Du,
    0x590Du, 0x5BCCu, 0x5E9Cu, 0x6276u, 0x629Au, 0x6D6Eu, 0x7B26u, 0x8986u,
    0x961Cu, 0x8299u, 0x592Bu, 0x8BE5u, 0x76D6u, 0x7518u, 0x8D63u, 0x5E72u,
    0x611Fu, 0x6E2Fu, 0x94A2u, 0x5188u, 0x5C97u, 0x9AD8u, 0x768Bu, 0x4E2Au,
    0x5404u, 0x54E5u, 0x683Cu, 0x6B4Cu, 0x845Bu, 0x9601u, 0x7ED9u, 0x66F4u,
    0x529Fu, 0x5DE5u, 0x516Cu, 0x5BABu, 0x5DE9u, 0x5F13u, 0x8D21u, 0x5171u,
    0x72D7u, 0x6C9Fu, 0x8C37u, 0x53E4u, 0x56FAu, 0x59D1u, 0x6545u, 0x6CBDu,
    0x9F13u, 0x74DCu, 0x839Eu, 0x5173u, 0x9986u, 0x500Cu, 0x51A0u, 0x704Cu,
    0x89C2u, 0x5E7Fu, 0x5149u, 0x6842u, 0x8D35u, 0x9B3Cu, 0x8F68u, 0x89C4u,
    0x56FDu, 0x90EDu, 0x8FC7u, 0x679Cu, 0x54C8u, 0x6D77u, 0x55E8u, 0x97E9u,
    0x6C49u, 0x90AFu, 0x884Cu, 0x676Du, 0x822Au, 0x597Du, 0x53F7u, 0x6D69u,
    0x548Cu, 0x5408u, 0x4F55u, 0x6CB3u, 0x8910u, 0x76D2u, 0x8377u, 0x83CFu,
    0x8D3Au, 0x8D6Bu, 0x9E64u, 0x79BEu, 0x9ED1u, 0x6A2Au, 0x8861u, 0x7EA2u,
    0x8679u, 0x5B8Fu, 0x6D2Au, 0x9E3Fu, 0x540Eu, 0x539Au, 0x5019u, 0x6CAAu,
    0x547Cu, 0x80E1u, 0x6E56u, 0x864Eu, 0x6237u, 0x4E92u, 0x58F6u, 0x72D0u,
    0x846Bu, 0x62A4u, 0x82B1u, 0x753Bu, 0x5316u, 0x534Eu, 0x6866u, 0x6ED1u,
    0x9A85u, 0x574Fu, 0x6000u, 0x6DEEu, 0x6362u, 0x8FD8u, 0x6853u, 0x73AFu,
    0x9EC4u, 0x8352u, 0x6F62u, 0x714Cu, 0x7687u, 0x51F0u, 0x4F1Au, 0x60E0u,
    0x7070u, 0x56DEu, 0x6062u, 0x5FBDu, 0x6C47u, 0x8F89u, 0x660Fu, 0x706Bu,
    0x83B7u, 0x970Du, 0x5409u, 0x5180u, 0x6D4Eu, 0x6025u, 0x7EE7u, 0x51E0u,
    0x7EA7u, 0x673Au, 0x9E21u, 0x5373u, 0x7EAAu, 0x53CAu, 0x57FAu, 0x6280u,
    0x66A8u, 0x6781u, 0x7A37u, 0x9645u, 0x96C6u, 0x84DFu, 0x5609u, 0x8D3Eu,
    0x5047u, 0x52A0u, 0x4F73u, 0x5BB6u, 0x90CFu, 0x9A7Eu, 0x67B6u, 0x68C0u,
    0x95F4u, 0x51CFu, 0x76D1u, 0x7B80u, 0x952Eu, 0x5251u, 0x5C16u, 0x5EFAu,
    0x4EF6u, 0x7586u, 0x848Bu, 0x6C5Fu, 0x964Du, 0x59DCu, 0x7EDBu, 0x8BB2u,
    0x53EBu, 0x86DFu, 0x4EA4u, 0x6912u, 0x7126u, 0x80F6u, 0x811Au, 0x89D2u,
    0x8F7Fu, 0x90CAu, 0x63A5u, 0x8857u, 0x501Fu, 0x8282u, 0x89E3u, 0x4ECBu,
    0x754Cu, 0x6D01u, 0x6854u, 0x8FD1u, 0x664Bu, 0x6D25u, 0x91D1u, 0x7D27u,
    0x8FDBu, 0x4EC5u, 0x7981u, 0x52B2u, 0x9526u, 0x7F19u, 0x4EACu, 0x8B66u,
    0x7CBEu, 0x7ECFu, 0x9759u, 0x4E95u, 0x666Fu, 0x6CFEu, 0x8346u, 0x83C1u,
    0x9756u, 0x5C31u, 0x65E7u, 0x6551u, 0x4E5Du, 0x9152u, 0x4FF1u, 0x53E5u,
    0x5C45u, 0x5DE8u, 0x70ACu, 0x805Au, 0x8392u, 0x5C40u, 0x77E9u, 0x5177u,
    0x6A58u, 0x6854u, 0x9104u, 0x89C9u, 0x90E1u, 0x541Bu, 0x4FCAu, 0x5361u,
    0x5580u, 0x5F00u, 0x51EFu, 0x770Bu, 0x520Au, 0x5EB7u, 0x8003u, 0x70E4u,
    0x53EFu, 0x514Bu, 0x79D1u, 0x5BA2u, 0x57A6u, 0x7A7Au, 0x63A7u, 0x5B54u,
    0x53E3u, 0x5E93u, 0x8DE8u, 0x5FEBu, 0x5BBDu, 0x77FFu, 0x594Eu, 0x6606u,
    0x6269u, 0x62ECu, 0x62C9u, 0x814Au, 0x6765u, 0x6D9Eu, 0x83B1u, 0x5170u,
    0x84DDu, 0x680Fu, 0x6984u, 0x6F9Cu, 0x89C8u, 0x5ECAu, 0x72FCu, 0x6717u,
    0x6D6Au, 0x90CEu, 0x9606u, 0x52B3u, 0x5D02u, 0x8001u, 0x4F6Cu, 0x4E86u,
    0x4E50u, 0x96F7u, 0x7C7Bu, 0x52D2u, 0x51B7u, 0x91CCu, 0x674Eu, 0x7ACBu,
    0x7483u, 0x529Bu, 0x4E3Du, 0x5229u, 0x68A8u, 0x6EA7u, 0x6FA7u, 0x7406u,
    0x8354u, 0x91B4u, 0x9ECEu, 0x8FDEu, 0x8054u, 0x6D9Fu, 0x83B2u, 0x94FEu,
    0x6881u, 0x91CFu, 0x4E24u, 0x4EAEu, 0x51C9u, 0x826Fu, 0x8FBDu, 0x7597u,
    0x5BEEu, 0x804Au, 0x5217u, 0x6797u, 0x4E34u, 0x96F6u, 0x5CADu, 0x9675u,
    0x94C3u, 0x4EE4u, 0x51CCu, 0x7075u, 0x67F3u, 0x5218u, 0x516Du, 0x6D41u,
    0x6D4Fu, 0x7559u, 0x9F99u, 0x9686u, 0x7B3Cu, 0x697Cu, 0x5A04u, 0x9C81u,
    0x6CF8u, 0x5362u, 0x8DEFu, 0x9732u, 0x7089u, 0x5E90u, 0x752Au, 0x82A6u,
    0x9646u, 0x9E7Fu, 0x9E93u, 0x7984u, 0x683Eu, 0x6EE6u, 0x4ED1u, 0x7F57u,
    0x6D1Bu, 0x6F2Fu, 0x841Du, 0x843Du, 0x5415u, 0x7387u, 0x7EFFu, 0x94DDu,
    0x95FEu, 0x65C5u, 0x6EE4u, 0x9A6Cu, 0x9EBBu, 0x7801u, 0x739Bu, 0x4E70u,
    0x5356u, 0x9EA6u, 0x6162u, 0x6EE1u, 0x5FD9u, 0x8292u, 0x732Bu, 0x6BDBu,
    0x5E3Du, 0x8302u, 0x6BCFu, 0x7164u, 0x6CA1u, 0x9B45u, 0x6885u, 0x6E44u,
    0x7709u, 0x7F8Eu, 0x4EECu, 0x95E8u, 0x8499u, 0x5B5Fu, 0x731Bu, 0x76DFu,
    0x5BC6u, 0x7C73u, 0x6C68u, 0x9762u, 0x7EF5u, 0x68C9u, 0x5195u, 0x6E11u,
    0x7720u, 0x514Du, 0x63CFu, 0x5E99u, 0x6DFCu, 0x95FDu, 0x6C11u, 0x95F5u,
    0x660Eu, 0x540Du, 0x547Du, 0x94EDu, 0x6A21u, 0x9ED8u, 0x58A8u, 0x6469u,
    0x6F20u, 0x725Fu, 0x6728u, 0x7261u, 0x62FFu, 0x90A3u, 0x5357u, 0x8111u,
    0x5185u, 0x90A3u, 0x80FDu, 0x4F60u, 0x9006u, 0x5462u, 0x62DFu, 0x5E74u,
    0x5FF5u, 0x9E1Fu, 0x5B81u, 0x725Bu, 0x6D53u, 0x519Cu, 0x722Cu, 0x5E15u,
    0x6392u, 0x62CDu, 0x6F58u, 0x76D8u, 0x6500u, 0x6CEEu, 0x78D0u, 0x87E0u,
    0x5224u, 0x8DD1u, 0x4F69u, 0x6C9Bu, 0x5F6Du, 0x670Bu, 0x84ECu, 0x9E4Fu,
    0x76AEu, 0x90B3u, 0x90EBu, 0x504Fu, 0x9891u, 0x576Au, 0x5E73u, 0x74F6u,
    0x82F9u, 0x5C4Fu, 0x5761u, 0x6CCAu, 0x9131u, 0x666Eu, 0x6D66u, 0x6FEEu,
    0x8386u, 0x84B2u, 0x8C31u, 0x542Fu, 0x4E03u, 0x5668u, 0x6C7Du, 0x6F06u,
    0x5176u, 0x4E93u, 0x5947u, 0x5D0Eu, 0x65D7u, 0x675Eu, 0x7941u, 0x7DA6u,
    0x9A91u, 0x9F50u, 0x7948u, 0x524Du, 0x9ED4u, 0x5343u, 0x6D45u, 0x6F5Cu,
    0x4E7Eu, 0x8FC1u, 0x9621u, 0x5F3Au, 0x5899u, 0x62A2u, 0x6865u, 0x6A35u,
    0x4E54u, 0x5207u, 0x6C81u, 0x79E6u, 0x94A6u, 0x9752u, 0x6E05u, 0x8F7Bu,
    0x6674u, 0x8BF7u, 0x5E86u, 0x60C5u, 0x743Cu, 0x79CBu, 0x4E18u, 0x7403u,
    0x90B1u, 0x53D6u, 0x533Au, 0x66F2u, 0x6710u, 0x6E20u, 0x8862u, 0x6CC9u,
    0x5168u, 0x5708u, 0x6743u, 0x786Eu, 0x7F3Au, 0x7FA4u, 0x71C3u, 0x8BA9u,
    0x9976u, 0x70EDu, 0x4EBAu, 0x4EC1u, 0x8BA4u, 0x4EFBu, 0x65E5u, 0x7ED2u,
    0x5BB9u, 0x6995u, 0x8363u, 0x84C9u, 0x5165u, 0x5982u, 0x6C5Du, 0x8F6Fu,
    0x745Eu, 0x6DA6u, 0x5F31u, 0x585Eu, 0x8D5Bu, 0x4E09u, 0x53C1u, 0x6851u,
    0x626Bu, 0x5AC2u, 0x8272u, 0x6C99u, 0x7802u, 0x838Eu, 0x9655u, 0x5C71u,
    0x5220u, 0x5584u, 0x6C55u, 0x6749u, 0x4E0Au, 0x5546u, 0x5C1Au, 0x5C11u,
    0x7ECDu, 0x90B5u, 0x97F6u, 0x70E7u, 0x5C04u, 0x820Du, 0x8BBEu, 0x6D89u,
    0x793Eu, 0x6C88u, 0x6DF1u, 0x4EC0u, 0x5BA1u, 0x795Eu, 0x8398u, 0x751Fu,
    0x5347u, 0x58F0u, 0x7701u, 0x5723u, 0x5D4Au, 0x76DBu, 0x80DCu, 0x662Fu,
    0x65F6u, 0x8BD5u, 0x5341u, 0x6E7Fu, 0x793Au, 0x5BA4u, 0x72EEu, 0x77F3u,
    0x5F0Fu, 0x89C6u, 0x58EBu, 0x5B9Eu, 0x5E02u, 0x5E08u, 0x65BDu, 0x6C0Fu,
    0x4E8Bu, 0x59CBu, 0x6536u, 0x5B88u, 0x517Du, 0x624Bu, 0x5BFFu, 0x6388u,
    0x9996u, 0x8F93u, 0x758Fu, 0x6811u, 0x66D9u, 0x6570u, 0x672Fu, 0x6CADu,
    0x719Fu, 0x8700u, 0x8212u, 0x5237u, 0x971Cu, 0x53CCu, 0x6C34u, 0x987Au,
    0x8BF4u, 0x6714u, 0x56DBu, 0x601Du, 0x4E1Du, 0x5BFAu, 0x65AFu, 0x6CD7u,
    0x79C1u, 0x53F8u, 0x5B8Bu, 0x9001u, 0x5D69u, 0x677Eu, 0x641Cu, 0x82CFu,
    0x5BBFu, 0x8083u, 0x901Fu, 0x7762u, 0x7EE5u, 0x9042u, 0x968Fu, 0x5B59u,
    0x7F29u, 0x7D22u, 0x9501u, 0x6240u, 0x4ED6u, 0x5B83u, 0x5854u, 0x53F0u,
    0x592Au, 0x6CF0u, 0x5F39u, 0x575Bu, 0x5766u, 0x6EE9u, 0x6F6Du, 0x90EFu,
    0x5510u, 0x5802u, 0x5858u, 0x6C64u, 0x5957u, 0x9676u, 0x6843u, 0x6ED4u,
    0x7279u, 0x6ED5u, 0x68AFu, 0x63D0u, 0x4F53u, 0x8E22u, 0x5929u, 0x6DFBu,
    0x7530u, 0x8DF3u, 0x6761u, 0x8C03u, 0x6311u, 0x94C1u, 0x542Cu, 0x505Cu,
    0x5385u, 0x5EADu, 0x4EADu, 0x8247u, 0x9706u, 0x94DCu, 0x901Au, 0x7EDFu,
    0x540Cu, 0x6850u, 0x6F7Cu, 0x5934u, 0x571Fu, 0x5F92u, 0x56E2u, 0x9000u,
    0x817Fu, 0x5C6Fu, 0x6258u, 0x9640u, 0x5916u, 0x7696u, 0x4E07u, 0x6E7Eu,
    0x665Au, 0x5B8Cu, 0x73A9u, 0x738Bu, 0x65FAu, 0x671Bu, 0x7F51u, 0x4E3Au,
    0x5371u, 0x5A01u, 0x9B4Fu, 0x7EF4u, 0x851Au, 0x56F4u, 0x5C3Eu, 0x536Bu,
    0x5C09u, 0x5FAEu, 0x672Au, 0x6D08u, 0x6E2Du, 0x6F4Du, 0x4F1Fu, 0x709Cu,
    0x6E29u, 0x7A33u, 0x6587u, 0x6211u, 0x5367u, 0x6DA1u, 0x6B66u, 0x68A7u,
    0x5434u, 0x4E94u, 0x5C4Bu, 0x65E0u, 0x96FEu, 0x4E4Cu, 0x4F0Du, 0x52A1u,
    0x543Eu, 0x609Fu, 0x821Eu, 0x829Cu, 0x7269u, 0x9E49u, 0x897Fu, 0x6EAAu,
    0x7EC6u, 0x5915u, 0x606Fu, 0x7CFBu, 0x6614u, 0x7199u, 0x9521u, 0x4E0Bu,
    0x53A6u, 0x590Fu, 0x971Eu, 0x5CE1u, 0x663Eu, 0x5148u, 0x53BFu, 0x73B0u,
    0x9650u, 0x4ED9u, 0x54B8u, 0x732Eu, 0x7EBFu, 0x8D24u, 0x6E58u, 0x5DF7u,
    0x60F3u, 0x5411u, 0x54CDu, 0x4E61u, 0x76F8u, 0x7965u, 0x8944u, 0x9879u,
    0x9999u, 0x8C61u, 0x5C0Fu, 0x6D88u, 0x6821u, 0x5B5Du, 0x8427u, 0x8C22u,
    0x5199u, 0x534Fu, 0x7023u, 0x65B0u, 0x4FE1u, 0x5FC3u, 0x5FFBu, 0x8F9Bu,
    0x884Cu, 0x5F62u, 0x578Bu, 0x5174u, 0x5E78u, 0x661Fu, 0x90A2u, 0x9649u,
    0x718Au, 0x5144u, 0x96C4u, 0x4FEEu, 0x4F11u, 0x79C0u, 0x5F90u, 0x8BB8u,
    0x9700u, 0x987Bu, 0x6E86u, 0x76F1u, 0x5BA3u, 0x9009u, 0x859Bu, 0x96EAu,
    0x5B66u, 0x8BAFu, 0x900Au, 0x4E9Au, 0x9E2Du, 0x538Bu, 0x57ADu, 0x5D16u,
    0x96C5u, 0x70DFu, 0x960Eu, 0x95EBu, 0x8A00u, 0x5043u, 0x5156u, 0x5830u,
    0x5CA9u, 0x5EF6u, 0x6F14u, 0x71D5u, 0x76D0u, 0x773Cu, 0x9A8Cu, 0x9633u,
    0x6768u, 0x6837u, 0x626Cu, 0x6D0Bu, 0x8981u, 0x836Fu, 0x59DAu, 0x5C27u,
    0x7A91u, 0x4E5Fu, 0x53F6u, 0x591Cu, 0x4E1Au, 0x9875u, 0x51B6u, 0x6396u,
    0x91CEu, 0x4E00u, 0x4E49u, 0x533Bu, 0x79FBu, 0x5F02u, 0x610Fu, 0x4EEAu,
    0x76CAu, 0x4F0Au, 0x4F9Du, 0x5937u, 0x5B9Cu, 0x6613u, 0x6C82u, 0x7719u,
    0x827Au, 0x9091u, 0x94F6u, 0x97F3u, 0x9634u, 0x5F15u, 0x8FCEu, 0x5E94u,
    0x82F1u, 0x8425u, 0x84E5u, 0x988Du, 0x9E70u, 0x9E66u, 0x7528u, 0x52C7u,
    0x6C38u, 0x6709u, 0x53F3u, 0x4F18u, 0x6CB9u, 0x53C8u, 0x53CBu, 0x5C24u,
    0x7531u, 0x8C6Bu, 0x6E1Du, 0x4F59u, 0x6B32u, 0x9C7Cu, 0x7389u, 0x96E8u,
    0x851Au, 0x8A89u, 0x4E8Eu, 0x8BEDu, 0x5C7Fu, 0x5CEAu, 0x6986u, 0x79B9u,
    0x79BAu, 0x7FBDu, 0x865Eu, 0x90C1u, 0x9884u, 0x6E14u, 0x6D74u, 0x5A31u,
    0x8FDCu, 0x8881u, 0x63F4u, 0x9662u, 0x56EDu, 0x613Fu, 0x82D1u, 0x5143u,
    0x539Fu, 0x5706u, 0x57A3u, 0x6C85u, 0x6E90u, 0x7CA4u, 0x5CB3u, 0x60A6u,
    0x6708u, 0x8D8Au, 0x5300u, 0x4E91u, 0x8FD0u, 0x90D3u, 0x97F5u, 0x5728u,
    0x8F7Du, 0x4ED4u, 0x6682u, 0x661Du, 0x85CFu, 0x65E9u, 0x566Au, 0x67A3u,
    0x6CFDu, 0x62E9u, 0x66FEu, 0x589Eu, 0x624Eu, 0x7A84u, 0x5BE8u, 0x7AD9u,
    0x6218u, 0x5360u, 0x5C55u, 0x6CBEu, 0x6E5Bu, 0x5F20u, 0x6A1Fu, 0x6F33u,
    0x7AE0u, 0x969Cu, 0x8D75u, 0x671Du, 0x5146u, 0x62DBu, 0x662Du, 0x7167u,
    0x8087u, 0x8FD9u, 0x7740u, 0x6D59u, 0x8005u, 0x771Fu, 0x5733u, 0x632Fu,
    0x9547u, 0x90D1u, 0x6B63u, 0x5F81u, 0x6574u, 0x7EB8u, 0x5236u, 0x6B62u,
    0x76F4u, 0x7F6Eu, 0x4E4Bu, 0x5CD9u, 0x5FD7u, 0x679Du, 0x6CBBu, 0x81F3u,
    0x81F4u, 0x82B7u, 0x6267u, 0x5740u, 0x503Cu, 0x652Fu, 0x4E2Du, 0x91CDu,
    0x79CDu, 0x5FE0u, 0x949Fu, 0x4F17u, 0x5DDEu, 0x5468u, 0x6D32u, 0x821Fu,
    0x73E0u, 0x6731u, 0x4E3Bu, 0x67F1u, 0x7AF9u, 0x732Au, 0x682Au, 0x8BF8u,
    0x9A7Bu, 0x8F6Cu, 0x4E13u, 0x5E84u, 0x88C5u, 0x51C6u, 0x6DBFu, 0x5353u,
    0x5B50u, 0x7D2Bu, 0x81EAu, 0x5B57u, 0x6893u, 0x6DC4u, 0x6ECBu, 0x8D44u,
    0x7EB5u, 0x8D70u, 0x90B9u, 0x7EC4u, 0x963Bu, 0x65CFu, 0x79DFu, 0x8DB3u,
    0x6700u, 0x5634u, 0x9075u, 0x5DE6u, 0x5EA7u, 0x5750u, 0x4F5Cu,
};

const uint16_t kPyCandidatesLen = 1359u;

/* Sorted pinyin table (binary-searchable). */
const PinyinEntry_t kPyTable[] = {
    { "\x61",   2,     0 },  /* a → 啊阿 */
    { "\x61\x69",   2,     2 },  /* ai → 隘爱 */
    { "\x61\x6e",   5,     4 },  /* an → 安暗按岸鞍 */
    { "\x61\x6f",   2,     9 },  /* ao → 傲澳 */
    { "\x62\x61",   8,    11 },  /* ba → 八坝把巴拔霸 */
    { "\x62\x61\x69",   4,    19 },  /* bai → 百白柏佰 */
    { "\x62\x61\x6e",   4,    23 },  /* ban → 半板班版 */
    { "\x62\x61\x6e\x67",   3,    27 },  /* bang → 帮榜蚌 */
    { "\x62\x61\x6f",   7,    30 },  /* bao → 保报包堡宝褒 */
    { "\x62\x65\x69",   7,    37 },  /* bei → 北被背备碑贝 */
    { "\x62\x65\x6e",   1,    44 },  /* ben → 本 */
    { "\x62\x69",   6,    45 },  /* bi → 毕壁必比碧闭 */
    { "\x62\x69\x61\x6e",   1,    51 },  /* bian → 边 */
    { "\x62\x69\x61\x6f",   2,    52 },  /* biao → 表标 */
    { "\x62\x69\x6e",   2,    54 },  /* bin → 宾滨 */
    { "\x62\x69\x6e\x67",   1,    56 },  /* bing → 兵 */
    { "\x62\x6f",   7,    57 },  /* bo → 波播薄玻亳博 */
    { "\x62\x75",   6,    64 },  /* bu → 不布步部埗埠 */
    { "\x63\x61\x69",   5,    70 },  /* cai → 蔡菜彩才裁 */
    { "\x63\x61\x6e",   1,    75 },  /* can → 餐 */
    { "\x63\x61\x6e\x67",   3,    76 },  /* cang → 仓沧苍 */
    { "\x63\x61\x6f",   2,    79 },  /* cao → 曹草 */
    { "\x63\x65",   2,    81 },  /* ce → 测侧 */
    { "\x63\x65\x6e",   1,    83 },  /* cen → 岑 */
    { "\x63\x65\x6e\x67",   1,    84 },  /* ceng → 层 */
    { "\x63\x68\x61",   3,    85 },  /* cha → 查茶差 */
    { "\x63\x68\x61\x69",   1,    88 },  /* chai → 柴 */
    { "\x63\x68\x61\x6e",   1,    89 },  /* chan → 禅 */
    { "\x63\x68\x61\x6e\x67",   5,    90 },  /* chang → 长常厂场昌 */
    { "\x63\x68\x61\x6f",   3,    95 },  /* chao → 巢潮超 */
    { "\x63\x68\x65",   1,    98 },  /* che → 车 */
    { "\x63\x68\x65\x6e",   3,    99 },  /* chen → 陈晨郴 */
    { "\x63\x68\x65\x6e\x67",   7,   102 },  /* cheng → 成程橙称城承 */
    { "\x63\x68\x69",   5,   109 },  /* chi → 池赤持坻驰 */
    { "\x63\x68\x6f\x6e\x67",   3,   114 },  /* chong → 虫充崇 */
    { "\x63\x68\x6f\x75",   1,   117 },  /* chou → 绸 */
    { "\x63\x68\x75",   5,   118 },  /* chu → 出储除楚滁 */
    { "\x63\x68\x75\x61\x6e",   2,   123 },  /* chuan → 川船 */
    { "\x63\x68\x75\x61\x6e\x67",   1,   125 },  /* chuang → 窗 */
    { "\x63\x68\x75\x6e",   1,   126 },  /* chun → 春 */
    { "\x63\x69",   2,   127 },  /* ci → 瓷慈 */
    { "\x63\x6f\x6e\x67",   1,   129 },  /* cong → 从 */
    { "\x63\x75",   1,   130 },  /* cu → 粗 */
    { "\x63\x75\x6e",   2,   131 },  /* cun → 村存 */
    { "\x63\x75\x6f",   1,   133 },  /* cuo → 错 */
    { "\x64\x61",   3,   134 },  /* da → 大打达 */
    { "\x64\x61\x69",   2,   137 },  /* dai → 带待 */
    { "\x64\x61\x6e",   5,   139 },  /* dan → 淡儋丹郸单 */
    { "\x64\x61\x6e\x67",   3,   144 },  /* dang → 党当砀 */
    { "\x64\x61\x6f",   5,   147 },  /* dao → 到道岛倒导 */
    { "\x64\x65",   2,   152 },  /* de → 的德 */
    { "\x64\x65\x6e\x67",   4,   154 },  /* deng → 邓登等灯 */
    { "\x64\x69",   6,   158 },  /* di → 地第底低弟迪 */
    { "\x64\x69\x61\x6e",   8,   164 },  /* dian → 滇点电巅典垫 */
    { "\x64\x69\x61\x6f",   1,   172 },  /* diao → 吊 */
    { "\x64\x69\x6e\x67",   5,   173 },  /* ding → 丁顶鼎叮定 */
    { "\x64\x6f\x6e\x67",   7,   178 },  /* dong → 东董栋洞动冬 */
    { "\x64\x6f\x75",   3,   185 },  /* dou → 豆斗窦 */
    { "\x64\x75",   5,   188 },  /* du → 都杜读度独 */
    { "\x64\x75\x61\x6e",   5,   193 },  /* duan → 短断段缎端 */
    { "\x64\x75\x69",   2,   198 },  /* dui → 对队 */
    { "\x64\x75\x6e",   3,   200 },  /* dun → 墩敦吨 */
    { "\x64\x75\x6f",   2,   203 },  /* duo → 多朵 */
    { "\x65",   2,   205 },  /* e → 鄂鹅 */
    { "\x65\x6e",   1,   207 },  /* en → 恩 */
    { "\x65\x72",   5,   208 },  /* er → 二尔洱耳儿 */
    { "\x66\x61",   2,   213 },  /* fa → 发法 */
    { "\x66\x61\x6e",   5,   215 },  /* fan → 返范反繁番 */
    { "\x66\x61\x6e\x67",   7,   220 },  /* fang → 防房放方坊芳 */
    { "\x66\x65\x69",   3,   227 },  /* fei → 飞肥非 */
    { "\x66\x65\x6e",   4,   230 },  /* fen → 粉分汾芬 */
    { "\x66\x65\x6e\x67",   9,   234 },  /* feng → 冯风峰凤丰奉 */
    { "\x66\x6f",   1,   243 },  /* fo → 佛 */
    { "\x66\x75",  15,   244 },  /* fu → 福傅副服复富 */
    { "\x67\x61\x69",   2,   259 },  /* gai → 该盖 */
    { "\x67\x61\x6e",   4,   261 },  /* gan → 甘赣干感 */
    { "\x67\x61\x6e\x67",   4,   265 },  /* gang → 港钢冈岗 */
    { "\x67\x61\x6f",   2,   269 },  /* gao → 高皋 */
    { "\x67\x65",   7,   271 },  /* ge → 个各哥格歌葛 */
    { "\x67\x65\x69",   1,   278 },  /* gei → 给 */
    { "\x67\x65\x6e\x67",   1,   279 },  /* geng → 更 */
    { "\x67\x6f\x6e\x67",   8,   280 },  /* gong → 功工公宫巩弓 */
    { "\x67\x6f\x75",   2,   288 },  /* gou → 狗沟 */
    { "\x67\x75",   7,   290 },  /* gu → 谷古固姑故沽 */
    { "\x67\x75\x61",   1,   297 },  /* gua → 瓜 */
    { "\x67\x75\x61\x6e",   7,   298 },  /* guan → 莞关馆倌冠灌 */
    { "\x67\x75\x61\x6e\x67",   2,   305 },  /* guang → 广光 */
    { "\x67\x75\x69",   5,   307 },  /* gui → 桂贵鬼轨规 */
    { "\x67\x75\x6f",   4,   312 },  /* guo → 国郭过果 */
    { "\x68\x61",   1,   316 },  /* ha → 哈 */
    { "\x68\x61\x69",   2,   317 },  /* hai → 海嗨 */
    { "\x68\x61\x6e",   3,   319 },  /* han → 韩汉邯 */
    { "\x68\x61\x6e\x67",   3,   322 },  /* hang → 行杭航 */
    { "\x68\x61\x6f",   3,   325 },  /* hao → 好号浩 */
    { "\x68\x65",  12,   328 },  /* he → 和合何河褐盒 */
    { "\x68\x65\x69",   1,   340 },  /* hei → 黑 */
    { "\x68\x65\x6e\x67",   2,   341 },  /* heng → 横衡 */
    { "\x68\x6f\x6e\x67",   5,   343 },  /* hong → 红虹宏洪鸿 */
    { "\x68\x6f\x75",   3,   348 },  /* hou → 后厚候 */
    { "\x68\x75",  11,   351 },  /* hu → 沪呼胡湖虎户 */
    { "\x68\x75\x61",   7,   362 },  /* hua → 花画化华桦滑 */
    { "\x68\x75\x61\x69",   3,   369 },  /* huai → 坏怀淮 */
    { "\x68\x75\x61\x6e",   4,   372 },  /* huan → 换还桓环 */
    { "\x68\x75\x61\x6e\x67",   6,   376 },  /* huang → 黄荒潢煌皇凰 */
    { "\x68\x75\x69",   8,   382 },  /* hui → 会惠灰回恢徽 */
    { "\x68\x75\x6e",   1,   390 },  /* hun → 昏 */
    { "\x68\x75\x6f",   3,   391 },  /* huo → 火获霍 */
    { "\x6a\x69",  20,   394 },  /* ji → 吉冀济急继几 */
    { "\x6a\x69\x61",   9,   414 },  /* jia → 嘉贾假加佳家 */
    { "\x6a\x69\x61\x6e",  10,   423 },  /* jian → 检间减监简键 */
    { "\x6a\x69\x61\x6e\x67",   7,   433 },  /* jiang → 疆蒋江降姜绛 */
    { "\x6a\x69\x61\x6f",  10,   440 },  /* jiao → 叫蛟交椒焦胶 */
    { "\x6a\x69\x65",   9,   450 },  /* jie → 接街借节解介 */
    { "\x6a\x69\x6e",  11,   459 },  /* jin → 近晋津金紧进 */
    { "\x6a\x69\x6e\x67",  11,   470 },  /* jing → 京警精经静井 */
    { "\x6a\x69\x75",   5,   481 },  /* jiu → 就旧救九酒 */
    { "\x6a\x75",  12,   486 },  /* ju → 俱句居巨炬聚 */
    { "\x6a\x75\x61\x6e",   1,   498 },  /* juan → 鄄 */
    { "\x6a\x75\x65",   1,   499 },  /* jue → 觉 */
    { "\x6a\x75\x6e",   3,   500 },  /* jun → 郡君俊 */
    { "\x6b\x61",   2,   503 },  /* ka → 卡喀 */
    { "\x6b\x61\x69",   2,   505 },  /* kai → 开凯 */
    { "\x6b\x61\x6e",   2,   507 },  /* kan → 看刊 */
    { "\x6b\x61\x6e\x67",   1,   509 },  /* kang → 康 */
    { "\x6b\x61\x6f",   2,   510 },  /* kao → 考烤 */
    { "\x6b\x65",   4,   512 },  /* ke → 可克科客 */
    { "\x6b\x65\x6e",   1,   516 },  /* ken → 垦 */
    { "\x6b\x6f\x6e\x67",   3,   517 },  /* kong → 空控孔 */
    { "\x6b\x6f\x75",   1,   520 },  /* kou → 口 */
    { "\x6b\x75",   1,   521 },  /* ku → 库 */
    { "\x6b\x75\x61",   1,   522 },  /* kua → 跨 */
    { "\x6b\x75\x61\x69",   1,   523 },  /* kuai → 快 */
    { "\x6b\x75\x61\x6e",   1,   524 },  /* kuan → 宽 */
    { "\x6b\x75\x61\x6e\x67",   1,   525 },  /* kuang → 矿 */
    { "\x6b\x75\x69",   1,   526 },  /* kui → 奎 */
    { "\x6b\x75\x6e",   1,   527 },  /* kun → 昆 */
    { "\x6b\x75\x6f",   2,   528 },  /* kuo → 扩括 */
    { "\x6c\x61",   2,   530 },  /* la → 拉腊 */
    { "\x6c\x61\x69",   3,   532 },  /* lai → 来涞莱 */
    { "\x6c\x61\x6e",   6,   535 },  /* lan → 兰蓝栏榄澜览 */
    { "\x6c\x61\x6e\x67",   6,   541 },  /* lang → 廊狼朗浪郎阆 */
    { "\x6c\x61\x6f",   4,   547 },  /* lao → 劳崂老佬 */
    { "\x6c\x65",   2,   551 },  /* le → 了乐 */
    { "\x6c\x65\x69",   3,   553 },  /* lei → 雷类勒 */
    { "\x6c\x65\x6e\x67",   1,   556 },  /* leng → 冷 */
    { "\x6c\x69",  14,   557 },  /* li → 里李立璃力丽 */
    { "\x6c\x69\x61\x6e",   5,   571 },  /* lian → 连联涟莲链 */
    { "\x6c\x69\x61\x6e\x67",   6,   576 },  /* liang → 梁量两亮凉良 */
    { "\x6c\x69\x61\x6f",   4,   582 },  /* liao → 辽疗寮聊 */
    { "\x6c\x69\x65",   1,   586 },  /* lie → 列 */
    { "\x6c\x69\x6e",   2,   587 },  /* lin → 林临 */
    { "\x6c\x69\x6e\x67",   7,   589 },  /* ling → 零岭陵铃令凌 */
    { "\x6c\x69\x75",   6,   596 },  /* liu → 柳刘六流浏留 */
    { "\x6c\x6f\x6e\x67",   3,   602 },  /* long → 龙隆笼 */
    { "\x6c\x6f\x75",   2,   605 },  /* lou → 楼娄 */
    { "\x6c\x75",  13,   607 },  /* lu → 鲁泸卢路露炉 */
    { "\x6c\x75\x61\x6e",   2,   620 },  /* luan → 栾滦 */
    { "\x6c\x75\x6e",   1,   622 },  /* lun → 仑 */
    { "\x6c\x75\x6f",   5,   623 },  /* luo → 罗洛漯萝落 */
    { "\x6c\x76",   7,   628 },  /* lv → 吕率绿铝闾旅 */
    { "\x6d\x61",   4,   635 },  /* ma → 马麻码玛 */
    { "\x6d\x61\x69",   3,   639 },  /* mai → 买卖麦 */
    { "\x6d\x61\x6e",   2,   642 },  /* man → 慢满 */
    { "\x6d\x61\x6e\x67",   2,   644 },  /* mang → 忙芒 */
    { "\x6d\x61\x6f",   4,   646 },  /* mao → 猫毛帽茂 */
    { "\x6d\x65\x69",   8,   650 },  /* mei → 每煤没魅梅湄 */
    { "\x6d\x65\x6e",   2,   658 },  /* men → 们门 */
    { "\x6d\x65\x6e\x67",   4,   660 },  /* meng → 蒙孟猛盟 */
    { "\x6d\x69",   3,   664 },  /* mi → 密米汨 */
    { "\x6d\x69\x61\x6e",   7,   667 },  /* mian → 面绵棉冕渑眠 */
    { "\x6d\x69\x61\x6f",   3,   674 },  /* miao → 描庙淼 */
    { "\x6d\x69\x6e",   3,   677 },  /* min → 闽民闵 */
    { "\x6d\x69\x6e\x67",   4,   680 },  /* ming → 明名命铭 */
    { "\x6d\x6f",   5,   684 },  /* mo → 模默墨摩漠 */
    { "\x6d\x6f\x75",   1,   689 },  /* mou → 牟 */
    { "\x6d\x75",   2,   690 },  /* mu → 木牡 */
    { "\x6e\x61",   2,   692 },  /* na → 拿那 */
    { "\x6e\x61\x6e",   1,   694 },  /* nan → 南 */
    { "\x6e\x61\x6f",   1,   695 },  /* nao → 脑 */
    { "\x6e\x65\x69",   2,   696 },  /* nei → 内那 */
    { "\x6e\x65\x6e\x67",   1,   698 },  /* neng → 能 */
    { "\x6e\x69",   4,   699 },  /* ni → 你逆呢拟 */
    { "\x6e\x69\x61\x6e",   2,   703 },  /* nian → 年念 */
    { "\x6e\x69\x61\x6f",   1,   705 },  /* niao → 鸟 */
    { "\x6e\x69\x6e\x67",   1,   706 },  /* ning → 宁 */
    { "\x6e\x69\x75",   1,   707 },  /* niu → 牛 */
    { "\x6e\x6f\x6e\x67",   2,   708 },  /* nong → 浓农 */
    { "\x70\x61",   2,   710 },  /* pa → 爬帕 */
    { "\x70\x61\x69",   2,   712 },  /* pai → 排拍 */
    { "\x70\x61\x6e",   7,   714 },  /* pan → 潘盘攀泮磐蟠 */
    { "\x70\x61\x6f",   1,   721 },  /* pao → 跑 */
    { "\x70\x65\x69",   2,   722 },  /* pei → 佩沛 */
    { "\x70\x65\x6e\x67",   4,   724 },  /* peng → 彭朋蓬鹏 */
    { "\x70\x69",   3,   728 },  /* pi → 皮邳郫 */
    { "\x70\x69\x61\x6e",   1,   731 },  /* pian → 偏 */
    { "\x70\x69\x6e",   1,   732 },  /* pin → 频 */
    { "\x70\x69\x6e\x67",   5,   733 },  /* ping → 坪平瓶苹屏 */
    { "\x70\x6f",   3,   738 },  /* po → 坡泊鄱 */
    { "\x70\x75",   6,   741 },  /* pu → 普浦濮莆蒲谱 */
    { "\x71\x69",  16,   747 },  /* qi → 启七器汽漆其 */
    { "\x71\x69\x61\x6e",   8,   763 },  /* qian → 前黔千浅潜乾 */
    { "\x71\x69\x61\x6e\x67",   3,   771 },  /* qiang → 强墙抢 */
    { "\x71\x69\x61\x6f",   3,   774 },  /* qiao → 桥樵乔 */
    { "\x71\x69\x65",   1,   777 },  /* qie → 切 */
    { "\x71\x69\x6e",   3,   778 },  /* qin → 沁秦钦 */
    { "\x71\x69\x6e\x67",   7,   781 },  /* qing → 青清轻晴请庆 */
    { "\x71\x69\x6f\x6e\x67",   1,   788 },  /* qiong → 琼 */
    { "\x71\x69\x75",   4,   789 },  /* qiu → 秋丘球邱 */
    { "\x71\x75",   6,   793 },  /* qu → 取区曲朐渠衢 */
    { "\x71\x75\x61\x6e",   4,   799 },  /* quan → 泉全圈权 */
    { "\x71\x75\x65",   2,   803 },  /* que → 确缺 */
    { "\x71\x75\x6e",   1,   805 },  /* qun → 群 */
    { "\x72\x61\x6e",   1,   806 },  /* ran → 燃 */
    { "\x72\x61\x6e\x67",   1,   807 },  /* rang → 让 */
    { "\x72\x61\x6f",   1,   808 },  /* rao → 饶 */
    { "\x72\x65",   1,   809 },  /* re → 热 */
    { "\x72\x65\x6e",   4,   810 },  /* ren → 人仁认任 */
    { "\x72\x69",   1,   814 },  /* ri → 日 */
    { "\x72\x6f\x6e\x67",   5,   815 },  /* rong → 绒容榕荣蓉 */
    { "\x72\x75",   3,   820 },  /* ru → 入如汝 */
    { "\x72\x75\x61\x6e",   1,   823 },  /* ruan → 软 */
    { "\x72\x75\x69",   1,   824 },  /* rui → 瑞 */
    { "\x72\x75\x6e",   1,   825 },  /* run → 润 */
    { "\x72\x75\x6f",   1,   826 },  /* ruo → 弱 */
    { "\x73\x61\x69",   2,   827 },  /* sai → 塞赛 */
    { "\x73\x61\x6e",   2,   829 },  /* san → 三叁 */
    { "\x73\x61\x6e\x67",   1,   831 },  /* sang → 桑 */
    { "\x73\x61\x6f",   2,   832 },  /* sao → 扫嫂 */
    { "\x73\x65",   1,   834 },  /* se → 色 */
    { "\x73\x68\x61",   3,   835 },  /* sha → 沙砂莎 */
    { "\x73\x68\x61\x6e",   6,   838 },  /* shan → 陕山删善汕杉 */
    { "\x73\x68\x61\x6e\x67",   3,   844 },  /* shang → 上商尚 */
    { "\x73\x68\x61\x6f",   5,   847 },  /* shao → 少绍邵韶烧 */
    { "\x73\x68\x65",   5,   852 },  /* she → 射舍设涉社 */
    { "\x73\x68\x65\x6e",   6,   857 },  /* shen → 沈深什审神莘 */
    { "\x73\x68\x65\x6e\x67",   8,   863 },  /* sheng → 生升声省圣嵊 */
    { "\x73\x68\x69",  19,   871 },  /* shi → 是时试十湿示 */
    { "\x73\x68\x6f\x75",   7,   890 },  /* shou → 收守兽手寿授 */
    { "\x73\x68\x75",  10,   897 },  /* shu → 输疏树曙数术 */
    { "\x73\x68\x75\x61",   1,   907 },  /* shua → 刷 */
    { "\x73\x68\x75\x61\x6e\x67",   2,   908 },  /* shuang → 霜双 */
    { "\x73\x68\x75\x69",   1,   910 },  /* shui → 水 */
    { "\x73\x68\x75\x6e",   1,   911 },  /* shun → 顺 */
    { "\x73\x68\x75\x6f",   2,   912 },  /* shuo → 说朔 */
    { "\x73\x69",   8,   914 },  /* si → 四思丝寺斯泗 */
    { "\x73\x6f\x6e\x67",   4,   922 },  /* song → 宋送嵩松 */
    { "\x73\x6f\x75",   1,   926 },  /* sou → 搜 */
    { "\x73\x75",   4,   927 },  /* su → 苏宿肃速 */
    { "\x73\x75\x69",   4,   931 },  /* sui → 睢绥遂随 */
    { "\x73\x75\x6e",   1,   935 },  /* sun → 孙 */
    { "\x73\x75\x6f",   4,   936 },  /* suo → 缩索锁所 */
    { "\x74\x61",   3,   940 },  /* ta → 他它塔 */
    { "\x74\x61\x69",   3,   943 },  /* tai → 台太泰 */
    { "\x74\x61\x6e",   6,   946 },  /* tan → 弹坛坦滩潭郯 */
    { "\x74\x61\x6e\x67",   4,   952 },  /* tang → 唐堂塘汤 */
    { "\x74\x61\x6f",   4,   956 },  /* tao → 套陶桃滔 */
    { "\x74\x65",   1,   960 },  /* te → 特 */
    { "\x74\x65\x6e\x67",   1,   961 },  /* teng → 滕 */
    { "\x74\x69",   4,   962 },  /* ti → 梯提体踢 */
    { "\x74\x69\x61\x6e",   3,   966 },  /* tian → 天添田 */
    { "\x74\x69\x61\x6f",   4,   969 },  /* tiao → 跳条调挑 */
    { "\x74\x69\x65",   1,   973 },  /* tie → 铁 */
    { "\x74\x69\x6e\x67",   7,   974 },  /* ting → 听停厅庭亭艇 */
    { "\x74\x6f\x6e\x67",   6,   981 },  /* tong → 铜通统同桐潼 */
    { "\x74\x6f\x75",   1,   987 },  /* tou → 头 */
    { "\x74\x75",   2,   988 },  /* tu → 土徒 */
    { "\x74\x75\x61\x6e",   1,   990 },  /* tuan → 团 */
    { "\x74\x75\x69",   2,   991 },  /* tui → 退腿 */
    { "\x74\x75\x6e",   1,   993 },  /* tun → 屯 */
    { "\x74\x75\x6f",   2,   994 },  /* tuo → 托陀 */
    { "\x77\x61\x69",   1,   996 },  /* wai → 外 */
    { "\x77\x61\x6e",   6,   997 },  /* wan → 皖万湾晚完玩 */
    { "\x77\x61\x6e\x67",   4,  1003 },  /* wang → 王旺望网 */
    { "\x77\x65\x69",  17,  1007 },  /* wei → 为危威魏维蔚 */
    { "\x77\x65\x6e",   3,  1024 },  /* wen → 温稳文 */
    { "\x77\x6f",   3,  1027 },  /* wo → 我卧涡 */
    { "\x77\x75",  16,  1030 },  /* wu → 武梧吴五屋无 */
    { "\x78\x69",   9,  1046 },  /* xi → 西溪细夕息系 */
    { "\x78\x69\x61",   5,  1055 },  /* xia → 下厦夏霞峡 */
    { "\x78\x69\x61\x6e",  10,  1060 },  /* xian → 显先县现限仙 */
    { "\x78\x69\x61\x6e\x67",  12,  1070 },  /* xiang → 湘巷想向响乡 */
    { "\x78\x69\x61\x6f",   5,  1082 },  /* xiao → 小消校孝萧 */
    { "\x78\x69\x65",   4,  1087 },  /* xie → 谢写协瀣 */
    { "\x78\x69\x6e",   5,  1091 },  /* xin → 新信心忻辛 */
    { "\x78\x69\x6e\x67",   8,  1096 },  /* xing → 行形型兴幸星 */
    { "\x78\x69\x6f\x6e\x67",   3,  1104 },  /* xiong → 熊兄雄 */
    { "\x78\x69\x75",   3,  1107 },  /* xiu → 修休秀 */
    { "\x78\x75",   6,  1110 },  /* xu → 徐许需须溆盱 */
    { "\x78\x75\x61\x6e",   2,  1116 },  /* xuan → 宣选 */
    { "\x78\x75\x65",   3,  1118 },  /* xue → 薛雪学 */
    { "\x78\x75\x6e",   2,  1121 },  /* xun → 讯逊 */
    { "\x79\x61",   6,  1123 },  /* ya → 亚鸭压垭崖雅 */
    { "\x79\x61\x6e",  14,  1129 },  /* yan → 烟阎闫言偃兖 */
    { "\x79\x61\x6e\x67",   5,  1143 },  /* yang → 阳杨样扬洋 */
    { "\x79\x61\x6f",   5,  1148 },  /* yao → 要药姚尧窑 */
    { "\x79\x65",   8,  1153 },  /* ye → 也叶夜业页冶 */
    { "\x79\x69",  17,  1161 },  /* yi → 一义医移异意 */
    { "\x79\x69\x6e",   4,  1178 },  /* yin → 银音阴引 */
    { "\x79\x69\x6e\x67",   8,  1182 },  /* ying → 迎应英营蓥颍 */
    { "\x79\x6f\x6e\x67",   3,  1190 },  /* yong → 用勇永 */
    { "\x79\x6f\x75",   8,  1193 },  /* you → 有右优油又友 */
    { "\x79\x75",  23,  1201 },  /* yu → 豫渝余欲鱼玉 */
    { "\x79\x75\x61\x6e",  13,  1224 },  /* yuan → 远袁援院园愿 */
    { "\x79\x75\x65",   5,  1237 },  /* yue → 粤岳悦月越 */
    { "\x79\x75\x6e",   5,  1242 },  /* yun → 匀云运郓韵 */
    { "\x7a\x61\x69",   3,  1247 },  /* zai → 在载仔 */
    { "\x7a\x61\x6e",   2,  1250 },  /* zan → 暂昝 */
    { "\x7a\x61\x6e\x67",   1,  1252 },  /* zang → 藏 */
    { "\x7a\x61\x6f",   3,  1253 },  /* zao → 早噪枣 */
    { "\x7a\x65",   2,  1256 },  /* ze → 泽择 */
    { "\x7a\x65\x6e\x67",   2,  1258 },  /* zeng → 曾增 */
    { "\x7a\x68\x61",   1,  1260 },  /* zha → 扎 */
    { "\x7a\x68\x61\x69",   2,  1261 },  /* zhai → 窄寨 */
    { "\x7a\x68\x61\x6e",   6,  1263 },  /* zhan → 站战占展沾湛 */
    { "\x7a\x68\x61\x6e\x67",   5,  1269 },  /* zhang → 张樟漳章障 */
    { "\x7a\x68\x61\x6f",   7,  1274 },  /* zhao → 赵朝兆招昭照 */
    { "\x7a\x68\x65",   4,  1281 },  /* zhe → 这着浙者 */
    { "\x7a\x68\x65\x6e",   4,  1285 },  /* zhen → 真圳振镇 */
    { "\x7a\x68\x65\x6e\x67",   4,  1289 },  /* zheng → 郑正征整 */
    { "\x7a\x68\x69",  17,  1293 },  /* zhi → 纸制止直置之 */
    { "\x7a\x68\x6f\x6e\x67",   6,  1310 },  /* zhong → 中重种忠钟众 */
    { "\x7a\x68\x6f\x75",   4,  1316 },  /* zhou → 州周洲舟 */
    { "\x7a\x68\x75",   9,  1320 },  /* zhu → 珠朱主柱竹猪 */
    { "\x7a\x68\x75\x61\x6e",   2,  1329 },  /* zhuan → 转专 */
    { "\x7a\x68\x75\x61\x6e\x67",   2,  1331 },  /* zhuang → 庄装 */
    { "\x7a\x68\x75\x6e",   1,  1333 },  /* zhun → 准 */
    { "\x7a\x68\x75\x6f",   2,  1334 },  /* zhuo → 涿卓 */
    { "\x7a\x69",   8,  1336 },  /* zi → 子紫自字梓淄 */
    { "\x7a\x6f\x6e\x67",   1,  1344 },  /* zong → 纵 */
    { "\x7a\x6f\x75",   2,  1345 },  /* zou → 走邹 */
    { "\x7a\x75",   5,  1347 },  /* zu → 组阻族租足 */
    { "\x7a\x75\x69",   2,  1352 },  /* zui → 最嘴 */
    { "\x7a\x75\x6e",   1,  1354 },  /* zun → 遵 */
    { "\x7a\x75\x6f",   4,  1355 },  /* zuo → 左座坐作 */
};

const uint16_t kPyTableLen = 334u;
