#!/usr/bin/env python3
"""extract_pinyin.py — Extract pinyin→Unicode mapping from Dondji cn_font_data.h
and emit App/ime/pinyin_table.c ready for binary-search IME.

Usage:
    python3 tools/extract_pinyin.py \
        --dondji /Users/jlee/projects/k5-dondji/App/cn_font_data.h \
        --out App/ime/pinyin_table.c
"""

import argparse
import re
import struct
import sys
from pathlib import Path
from typing import Dict, List, Tuple


# ---------------------------------------------------------------------------
# Step 1 — parse font index: comment → font_idx → Unicode
# ---------------------------------------------------------------------------

def parse_font_index(header_text: str) -> Dict[int, int]:
    """
    Extract font_idx → Unicode from bitmap comment lines like:
        /* [  0] '的' U+7684 */
        /* [  1] '是' U+662F */
    Returns {font_idx: unicode_cp}.
    """
    pattern = re.compile(r'/\*\s*\[\s*(\d+)\]\s+.*?U\+([0-9A-Fa-f]+)\s*\*/')
    mapping: Dict[int, int] = {}
    for m in pattern.finditer(header_text):
        idx = int(m.group(1))
        cp  = int(m.group(2), 16)
        mapping[idx] = cp
    return mapping


# ---------------------------------------------------------------------------
# Step 2 — parse cn_pinyin_data bytes
# ---------------------------------------------------------------------------

def extract_c_byte_array(header_text: str, varname: str) -> bytes:
    """Pull out the raw bytes of a static const uint8_t array from C source."""
    # Find the array body between { and };
    pat = re.compile(
        r'static\s+const\s+uint8_t\s+' + re.escape(varname) + r'\s*\[.*?\]\s*=\s*\{(.*?)\};',
        re.DOTALL
    )
    m = pat.search(header_text)
    if not m:
        raise ValueError(f"Cannot find array {varname!r} in header")
    body = m.group(1)
    # Extract only 0x hex literals (the pinyin array uses exclusively hex values).
    # Using \b\d+\b here is unsafe because it would match numbers in comments.
    values = re.findall(r'0x[0-9A-Fa-f]+', body)
    return bytes(int(v, 16) for v in values)


def parse_pinyin_table(raw: bytes) -> List[Tuple[str, List[int]]]:
    """
    Parse Dondji's cn_pinyin_data binary.
    Format per entry:
        [str_len : 1]  [syllable : str_len]  [char_count : 1]  [indices : char_count*2]
    indices are big-endian uint16 font indices.
    Returns list of (syllable_str, [font_idx, ...]) sorted by file order.
    """
    entries = []
    i = 0
    n = len(raw)
    while i < n:
        str_len = raw[i]; i += 1
        if str_len == 0 or i + str_len > n:
            break
        syllable = raw[i:i+str_len].decode('ascii'); i += str_len
        char_count = raw[i]; i += 1
        font_indices = []
        for _ in range(char_count):
            if i + 2 > n:
                break
            font_idx = (raw[i] << 8) | raw[i+1]; i += 2
            font_indices.append(font_idx)
        entries.append((syllable, font_indices))
    return entries


# ---------------------------------------------------------------------------
# Step 3 — combine and sort
# ---------------------------------------------------------------------------

def build_pinyin_unicode_map(
    font_idx_to_cp: Dict[int, int],
    pinyin_entries: List[Tuple[str, List[int]]],
) -> List[Tuple[str, List[int]]]:
    """
    Convert (syllable, [font_idx]) → (syllable, [unicode_cp]).
    Drops any font_idx not in the index map (shouldn't happen with complete data).
    Sorts result by syllable string.
    """
    result = []
    for syllable, font_indices in pinyin_entries:
        cps = []
        for fi in font_indices:
            cp = font_idx_to_cp.get(fi)
            if cp is not None:
                cps.append(cp)
        if cps:
            result.append((syllable, cps))
    result.sort(key=lambda x: x[0])
    return result


# ---------------------------------------------------------------------------
# Step 4 — emit C source
# ---------------------------------------------------------------------------

HEADER = """\
/* Auto-generated by tools/extract_pinyin.py — do not edit.
 * Regenerate:
 *   python3 tools/extract_pinyin.py \\
 *       --dondji /path/to/k5-dondji/App/cn_font_data.h \\
 *       --out App/ime/pinyin_table.c
 *
 * Table: {count} syllables, {total_cands} total codepoints.
 * Sorted by syllable string (binary search in O(log {count}) ≈ {bsearch_steps} steps).
 * All data is const, placed in MCU Flash (.rodata) — zero SPI reads for lookup.
 *
 * Source: Dondji cn_font_data.h, codepoint extraction via font-index comments.
 * SPDX-License-Identifier: Apache-2.0
 */

#include "ime/pinyin_table.h"
"""

def emit_c(entries: List[Tuple[str, List[int]]], out_path: Path) -> None:
    import math
    count = len(entries)
    total_cands = sum(len(cps) for _, cps in entries)
    bsearch_steps = math.ceil(math.log2(count)) if count > 0 else 0

    lines = [HEADER.format(count=count, total_cands=total_cands,
                           bsearch_steps=bsearch_steps)]

    # --- flat candidates array ---
    lines.append("/* Flat array of all candidate Unicode codepoints.")
    lines.append(" * kPyTable[i].offset is the start index; kPyTable[i].count is the length. */")
    lines.append("const uint16_t kPyCandidates[] = {")
    offsets = []
    flat = []
    for syl, cps in entries:
        offsets.append(len(flat))
        flat.extend(cps)
    # Emit 8 per line
    for start in range(0, len(flat), 8):
        chunk = flat[start:start+8]
        line = "    " + ", ".join(f"0x{cp:04X}u" for cp in chunk) + ","
        lines.append(line)
    lines.append("};\n")
    lines.append(f"const uint16_t kPyCandidatesLen = {len(flat)}u;\n")

    # --- table ---
    lines.append("/* Sorted pinyin table (binary-searchable). */")
    lines.append("const PinyinEntry_t kPyTable[] = {")
    for i, ((syl, cps), off) in enumerate(zip(entries, offsets)):
        count_i = len(cps)
        # Render syllable as a C string with hex escapes for safety
        syl_c = ''.join(f'\\x{ord(c):02x}' for c in syl)
        chars_preview = ''.join(chr(cp) if 0x4E00 <= cp <= 0x9FFF else '?' for cp in cps[:6])
        lines.append(f'    {{ "{syl_c}", {count_i:3d}, {off:5d} }},  /* {syl} → {chars_preview} */')
    lines.append("};\n")
    lines.append(f"const uint16_t kPyTableLen = {count}u;\n")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Written {out_path}: {count} syllables, {total_cands} codepoints, "
          f"{out_path.stat().st_size} bytes", file=sys.stderr)


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dondji", required=True,
                    help="Path to k5-dondji/App/cn_font_data.h")
    ap.add_argument("--out", required=True,
                    help="Output path for pinyin_table.c (e.g. App/ime/pinyin_table.c)")
    args = ap.parse_args()

    header_text = Path(args.dondji).read_text(encoding="utf-8", errors="replace")

    print("Parsing font index (font_idx → Unicode) …", file=sys.stderr)
    font_idx_to_cp = parse_font_index(header_text)
    print(f"  {len(font_idx_to_cp)} glyph entries found", file=sys.stderr)

    print("Parsing cn_pinyin_data bytes …", file=sys.stderr)
    raw = extract_c_byte_array(header_text, "cn_pinyin_data")
    print(f"  {len(raw)} bytes", file=sys.stderr)

    pinyin_entries = parse_pinyin_table(raw)
    print(f"  {len(pinyin_entries)} syllables parsed", file=sys.stderr)

    print("Building syllable → Unicode mapping …", file=sys.stderr)
    entries = build_pinyin_unicode_map(font_idx_to_cp, pinyin_entries)
    print(f"  {len(entries)} syllables with Unicode candidates", file=sys.stderr)

    out_path = Path(args.out)
    emit_c(entries, out_path)


if __name__ == "__main__":
    main()
